version: '2'
services:
  shploader:
    build:
      context: ../backend
      dockerfile: ../deployment/Dockerfile
    image: shploader:latest
    ports:
      - "8095:8095"
    restart: always
    volumes:
      - "D:\\projekty\\shploader\\shploader\\deployment\\conf:/volume/conf"
      - "D:\\rozne\\2025-wrzesnia\\2025-09-shp\\PWiK\\SHAPE GESUT:/volume/gesut"
      - "D:\\rozne\\2025-wrzesnia\\2025-09-shp\\PWiK\\shp_swde\\nowe-cp1250:/volume/swde"
      - "D:\\rozne\\2025-wrzesnia\\2025-09-shp\\PWiK\\SHAPE BDOT500:/volume/sytuacja"
